{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  tls:
    - hosts:
      - {{ .Values.ingress.host | quote }}
      secretName: {{ .Release.Name }}-ingress
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
        {{- if .Values.frontend.enabled }}
          - backend:
              service:
                name: {{ .Release.Name }}-frontend
                port:
                  number: {{ .Values.frontend.service.port }}
            path: {{ .Values.ingress.paths.frontend }}        
            pathType: ImplementationSpecific
        {{- end }}
        {{- if .Values.core.enabled }}
          - backend:
              service:
                name: {{ .Release.Name }}-core
                port:
                  number: {{ .Values.core.service.port }}
            path: {{ .Values.ingress.paths.core }}        
            pathType: ImplementationSpecific
        {{- end }}
          

{{- end }}